---
- name: "Start conversion"
  hosts: convertlamp.parmstrong.ca
  gather_facts: true
  become: true
  
  vars_files:
  - vars/vault.yml
  - vars/main.yml
  
  vars:
    ansible_python_interpreter: /usr/bin/python
  
  tasks:
    - name: "Confirm prerequisites"
      ansible.builtin.include_tasks: "tasks/ensure_prereqs.yml"

    - name: "Perform pre-conversion tasks"
      ansible.builtin.include_tasks: "tasks/pre_convert_tasks.yml"

    - name: "Convert systems"
      ansible.builtin.include_tasks: "tasks/convert.yml"

    - name: "Perform post-conversion tasks"
      ansible.builtin.include_tasks: "tasks/post_convert_tasks.yml"

    - name: "Verify Conversion"
      ansible.builtin.include_tasks: "tasks/convert_verify.yml"

    - name: "Commit Conversion"
      ansible.builtin.include_tasks: "tasks/convert_commit.yml"