---
# Install wordpress from our currated EPEL content view 
# we will only allow Wordpress and its dependencies from the content view

- name: Download WordPress
  ansible.builtin.get_url: 
    url: "http://wordpress.org/wordpress-{{ wp_version }}.tar.gz"
    dest: "/srv/wordpress-{{ wp_version }}.tar.gz"
    sha256sum: "{{ wp_sha256sum }}"

- name: Extract archive
  ansible.builtin.command: 
    chdir: "/srv/"
    cmd: "/bin/tar xvf wordpress-{{ wp_version }}.tar.gz"
    creates: "/srv/wordpress"

- name: Add group "wordpress"
  ansible.builtin.group: 
    name: "wordpress"

- name: Add user "wordpress"
  ansible.builtin.user: 
    name: "wordpress"
    group: "wordpress"
    home: "/srv/wordpress/"

- name: Fetch random salts for WordPress config
  command: "curl https://api.wordpress.org/secret-key/1.1/salt/"
  register: "wp_salt"
  delegate_to: localhost

- name: Create WordPress database
  community.mysql.mysql_db: 
    name: "{{ wp_db_name }}"
    state: present

- name: Create WordPress database user
  community.mysql.mysql_user: 
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL" 
    host: "localhost"
    state: present

- name: Copy WordPress config file
  ansible.builtin.template: 
    src: "wp-config.php"
    dest: "/srv/wordpress/"

- name: Change ownership of WordPress installation
  ansible.builtin.file: 
    path: "/srv/wordpress/"
    owner: "wordpress"
    group: "wordpress"
    state: directory
    recurse: yes

- name: install python SELinux utilities RHEL 8
  ansible.builtin.yum: 
    pkg: "python3-policycoreutils"
    state: present
  when: ansible_distribution_major_version == "8"

- name: install python SELinux utilities RHEL7
  ansible.builtin.yum: 
    pkg: "policycoreutils-python"
    state: present
  when: ansible_distribution_major_version == "7"

- name: install the php mysql extension RHEL8
  ansible.builtin.yum: 
    pkg: "php-mysqlnd"
    state: present
  when: ansible_distribution_major_version == "8"

- name: install the php mysql extension RHEL7
  ansible.builtin.yum: 
    pkg: "php-mysql"
    state: present
  when: ansible_distribution_major_version == "7"

# update to SELinux modules
- name: set the SELinux policy for the Wordpress directory
  community.general.sefcontext: 
    setype: "httpd_sys_content_t" 
    target: "/srv/wordpress(/.*)?"
    state: present

- name: set the SELinux policy for wp-config.php
  community.general.sefcontext: 
    setype: "httpd_sys_script_exec_t" 
    target: "/srv/wordpress/wp-config.php"
    state: present

- name: set the SELinux policy for wp-content directory
  community.general.sefcontext: 
    setype: "httpd_sys_rw_content_t"
    target: "/srv/wordpress/wp-content(/.*)?"
    state: present

- name: set the SELinux policy for the *.php files
  community.general.sefcontext: 
    setype: "httpd_sys_script_exec_t"
    target: "/srv/wordpress/*.php"
    state: present

- name: set the SELinux policy for the Upgrade directory
  community.general.sefcontext: 
    setype: "httpd_sys_rw_content_t"
    target: "/srv/wordpress/wp-content/upgrade(/.*)?"
    state: present

- name: set the SELinux policy for the Uploads directory
  community.general.sefcontext: 
    setype: "httpd_sys_rw_content_t"
    target: "/srv/wordpress/wp-content/uploads(/.*)?"
    state: present

- name: set the SELinux policy for the wp-includes php files
  community.general.sefcontext: 
    setype: "httpd_sys_script_exec_t"
    target: "/srv/wordpress/wp-includes/*.php"
    state: present

- name: set the SELinux on all the Files
  ansible.builtin.command: "restorecon -Rv /srv/wordpress"

- name: Start php-fpm Service
  ansible.builtin.service: 
    name: "php-fpm"
    state: started 
    enabled: yes
