---
# The systems have to have these repos in the content view.

- name: Ensure repos are available on RHEL 8
  community.general.rhsm_repository:
    name:
      - "{{ epel8_rpms_repo_name }}"
      - "{{ epel8_streams_repo_name }}"
  when: ansible_distribution_major_version == "8"

- name: Ensure repos are available on RHEL 7
  community.general.rhsm_repository:
    name: "{{ epel7_rpms_repo_name }}"
  when: ansible_distribution_major_version == "7"

- name: Install Firewalld
  ansible.builtin.yum:
    name: firewalld
    state: present

- name: Firewalld service state
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true
