# This task sets up our convert2rhel demo environment.

# Without special configuration, when a CentOS system is deployed from a Satellite, it actually still uses the upstream
# repos to get its content. We must
# - install the satellite keys
# - register the system to the satellite
# - attach it to the proper content view
# Thankfully, when setup for IdM registration and with our satellite using kerberos for remote execution, our 
# remote execution works fine :-)

