# this task makes sure a number of repos and binaries are installed on our test systems to 
# make life easier for our demo.

# typically these sorts of things are uncovered during initial conversion tests and system discovery.

- name: "Install the Satellite components"
  ansible.builtin.yum:
    name: 
      - "https://sat6.parmstrong.ca/pub/katello-ca-consumer-latest.noarch.rpm"
      - "subscription-manager"
    state: present

- name: "Register to the satellite"
  community.general.redhat_subscription:
    org_id: "Default_Organization"
    activationkey: "CentOS79"

- name: "Install the components from Satellite"
  ansible.builtin.yum:
    name: 
      - "python2-pip"
    state: present