# This task ensures that all the convert2RHEL prerequisites are in place
# If any task fails the host is flagged for review

- name: "Assert that we are trying to convert a supported release"
  ansible.builtin.assert:
    that: 
      - ansible_architecture == "x86_64"
      - (ansible_distribution == "Oracle" and ansible_distribution_version in ["7.9", "8.8"]) 
        or (ansible_distribution == "CentOS" and ansible_distribution_version in ["7.9", "8.5"])
        or (ansible_distribution == "Alma" and ansible_distribution_version in ["8.6", "8.8"])
        or (ansible_distribution == "Rocky" and ansible_distribution_version in ["8.6", "8.8"])

- name: "Ensure the sos package is installed"
  ansible.builtin.yum:
    name: sos
    state: present