# This task ensures all the pre-conversion tasks have taken place
# the first task is to create a snapshot of the appropriate type
# Additional tasks my be specified for a given system
# if any task fails from here on, we set the rollback flag to revert the snapshot

