---
# Perform the power action 
# one of powered-off, powered-on, reboot-guest, restarted, shutdown-guest, suspended, present (default == powered-on)
- set_fact:
    force: false

- name: Find Guest's Folder using name
  community.vmware.vmware_guest_find:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    name: "{{ item.name }}"
  delegate_to: localhost
  register: vm_folder

- set_fact:
    force: true
  when: current_state == "powered-on"

- name: "Power Action - power state set to: {{ current_state }} for host: {{ item.name }}"
  community.vmware.vmware_guest_powerstate:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ datacenter_name }}"
    folder: "{{ datacenter_folder }}"
    name: "{{ item.name }}"
    state: "{{ current_state }}"
    force: "{{ force }}"
  delegate_to: localhost