---
# do the actual snapshot action - one of present, absent, revert, remove_all
  - name: "Snapshot Action - snapshot state set to: {{ current_state }} for host: {{ item.name }}"
    community.vmware.vmware_guest_snapshot:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ datacenter_name }}"
      folder: "{{ datacenter_folder }}"
      name: "{{ item.name }}"
      state: "{{ current_state }}"
      snapshot_name: "{{ item.snap_name }}"
      description: "{{ item.snap_description }}"
      quiesce: "{{ item.quiesce }}"
      validate_certs: false
    delegate_to: 127.0.0.1