---
# Variables listed here are applicable to all host groups
epel8_rpms_repo_name: "Default_Organization_EPEL8_EPEL8"
epel8_streams_repo_name: "Default_Organization_EPEL8_EPEL8_Streams"

epel7_rpms_repo_name: "Default_Organization_EPEL7_EPEL7"

wp_version: 4.6
wp_sha256sum: c1856cf969b1e73025ba2c681491908c3a4a6c5a2333f4531bf9bfb90f634380

# MySQL settings
mysqlservice: mysqld
mysql_port: 3306

# These are the WordPress database settings
wp_db_name: "{{ vault_wp_db_name }}"
wp_db_user: "{{ vault_wp_db_user }}"
wp_db_password: "{{ vault_wp_db_password }}"

# These are the WordPress default weblog settings
wp_weblog_title: "SampleSite"
wp_user_name: "anonuser"
wp_admin_password: "S33kr8"
wp_allow_weak_pass: true
wp_admin_email: "joeuser@parmstrong.ca"
wp_blog_public: false

# This is used for the nginx server configuration, but access to the
# WordPress site is not restricted by a named host.
nginx_port: 80
server_hostname: "{{ ansible_fqdn }}"
acm_nginx_conf_file: "acm.conf"

# Disable All Updates
# By default automatic updates are enabled, set this value to true to disable all automatic updates
auto_up_disable: false

#Define Core Update Level
# true  = Development, minor, and major updates are all enabled
# false = Development, minor, and major updates are all disabled
# minor = Minor updates are enabled, development, and major updates are disabled
core_update_level: true
