---
# These tasks install http and the php modules.

- name: Install httpd and php for RHEL 7
  ansible.builtin.yum: 
    name:
    - httpd
    - php
    - php-mysql
    state: latest
  when: ansible_distribution_major_version == "7"

- name: Install httpd and php for RHEL 8
  ansible.builtin.dnf: 
    name:
    - "httpd"
    - "@php:7.4/common"
    state: present
  when: ansible_distribution_major_version == "8"

- name: ensure php modules for RHEL 8
  ansible.builtin.dnf: 
    name:
    - "php"
    - "php-mysqlnd"
    - "php-mbstring"
    - "php-opcache"
    - "php-gd"
    state: present
  when: ansible_distribution_major_version == "8"

- name: Start firewalld
  ansible.builtin.service: 
    name: firewalld 
    state: started 
    enabled: true

- name: insert firewalld rule for httpd
  ansible.posix.firewalld: 
    port: "{{ httpd_port }}/tcp"
    permanent: true
    immediate: true
    state: enabled

- name: http service state
  ansible.builtin.service: 
    name: httpd 
    state: started 
    enabled: true

- name: Configure SELinux to allow httpd to connect to remote database
  ansible.posix.seboolean: 
    name: httpd_can_network_connect_db 
    state: true 
    persistent: true
