---
# We will use modules for RHEL8
- name: Install MariaDB packages for RHEL7
  ansible.builtin.yum: 
    name: 
    - "policycoreutils-python"
    - "mariadb-server"
    - "python"
    - "MySQL-python"
    state: latest
  when: ansible_distribution_major_version == "7"

# python3-PyMySQL included in python36 module
- name: Install MariaDB AppStreams for RHEL 8
  ansible.builtin.dnf: 
    name: 
    - "@mariadb:10.3/server"
    - "@python36:3.6/common"
    state: present                                # Must be present NOT latest or will fail - this is a bug https://github.com/ansible/ansible/issues/56504
  when: ansible_distribution_major_version == "8"

- name: Ensure python3-PyMySQL is really, really there. Because apparently its not
  ansible.builtin.command: "pip3 install PyMySQL"
  when: ansible_distribution_major_version == "8"
  
- name: Configure SELinux to allow mysql port {{ mysql_port }}
  community.general.seport: 
    ports: "{{ mysql_port }}"
    proto: tcp 
    setype: mysqld_port_t
    state: present

- name: Ensure the proper log directory
  ansible.builtin.file:
    path: "/var/log/mysqld/"
    state: directory
    owner: mysql
    group: mysql

- name: Ensure the proper pid directory
  ansible.builtin.file:
    path: "/var/run/mysqld/"
    state: directory
    owner: mysql
    group: mysql
    
- name: Deploy the Mysql configuration file
  ansible.builtin.template: 
    src: my.cnf.j2 
    dest: /etc/my.cnf
  notify:
  - restart mariadb

- name: Start MariaDB Service
  ansible.builtin.service:
    name: mariadb 
    state: started
    enabled: true

- name: Ensure firewalld has been started in order to add rules
  ansible.builtin.service: 
    name: firewalld
    state: started
    enabled: true

- name: Add firewall rules
  ansible.posix.firewalld: 
    port: "{{ mysql_port }}/tcp"
    permanent: true
    immediate: true
    state: enabled

- name: Create Application Database
  community.mysql.mysql_db: 
    name: "{{ dbname }}"
    state: present

- name: Create Application DB User
  community.mysql.mysql_user:
    name: "{{ dbuser }}"
    password: "{{ upassword }}"
    sql_log_bin: false
    priv: "*.*:ALL"
    host: "{{ ansible_fqdn }}"
    state: present

- name: Copy the sample database build files
  ansible.builtin.copy: 
    src: files/{{ item }} 
    dest: /root/{{ item }}
  loop:
    - nation.sql

- name: Create and Populate the sample database
  community.mysql.mysql_db:
    state: import
    name: all
    target: /root/nation.sql

- name: Install Grafana if requested
  include_tasks: install_grafana.yml
  when: install_grafana == true
  
