---
# We will use modules for RHEL8
- name: Install MariaDB packages for RHEL7
  ansible.builtin.yum: 
    name: 
    - "mariadb-server"
    - "python"
    - "MySQL-python"
    state: latest
  when: ansible_distribution_major_version == "7"

- name: Install MariaDB AppStreams for RHEL 8
  ansible.builtin.dnf: 
    name: 
    - "@mariadb:10.3/server"
    - "@python36:3.6/common"
    state: present                                # Must be present NOT latest or will fail - this is a bug https://github.com/ansible/ansible/issues/56504
  when: ansible_distribution_major_version == "8"

# - name: Ensure Python3 is the default python on RHEL8 because sample app is old
#   ansible.builtin.command: "alternatives --set python /usr/bin/python3"
#   when: ansible_distribution_major_version == "8"
- name: Install python3-PyMySQL
  command: "pip3 install PyMySQL"

- name: Configure SELinux to allow mysql port {{ mysql_port }}
  community.general.seport: 
    ports: "{{ mysql_port }}"
    proto: tcp 
    setype: mysqld_port_t
    state: present

- name: Deploy the Mysql configuration file
  ansible.builtin.template: 
    src: my.cnf.j2 
    dest: /etc/my.cnf
  notify:
  - restart mariadb

- name: Start MariaDB Service
  ansible.builtin.service:
    name: mariadb 
    state: started
    enabled: true

- name: Ensure firewalld has been started in order to add rules
  ansible.builtin.service: 
    name: firewalld
    state: started
    enabled: true

- name: Add firewall rules
  ansible.posix.firewalld: 
    port: "{{ mysql_port }}/tcp"
    permanent: true
    immediate: true
    state: enabled
